openapi: 3.0.0
servers:
  - description: development
    url: http://localhost:8080/api/v1
info:
  description: CleevioApi
  version: "1.0.0"
  title: CleevioProductManagement
  contact:
    email: richardskrivanek@icloud.com

  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: managers
    description: Operations available only for managers
  - name: employees
    description: Operations available for employees
paths:
  /api/v1/save/item:
    post:
      tags:
        - managers
      summary: adds an inventory item
      operationId: addInventory
      description: Adds an item to the system
      responses:
        '201':
          description: item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryItemDto'
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItemDto'
        description: Inventory item to add
  /api/v1/inventory/{searchText}:
    get:
      tags:
        - employees
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      parameters:
        - in: path
          name: searchText
          description: pass an optional name of product for looking up inventory
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryItemDto'
        '400':
          description: bad input parameter
  /api/v1/inventory:
    get:
      tags:
        - employees
      summary: searches inventory
      operationId: getAll
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryItemDto'
        '400':
          description: bad input parameter
components:
  schemas:
    InventoryItemDto:
      type: object
      required:
        - name
        - description
        - price
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Banana
        description:
          type: string
          example: fruit
        price:
          type: number
          format: double
          example: 12.90
        dateOfCreation:
          type: string
          format: date
          example: "2016-08-29"  # ISO 8601 date format
